[global]
# Streamlit Configuration for Dashboard Gestión Carnicería
# Optimized for production deployment

[server]
# Server configuration
port = 8501
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
# Browser configuration
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
# Theme configuration
primaryColor = "#2E86AB"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[logger]
# Logger configuration
level = "info"

[client]
# Client configuration
showErrorDetails = true
toolbarMode = "minimal"

[runner]
# Runner configuration
magicEnabled = true
# Force refresh Thu Oct  2 20:06:30 WEST 2025
